# Generated by Django 5.2.7 on 2025-10-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
