# Generated by Django 5.2.7 on 2025-10-15 12:46

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['name'], 'verbose_name': 'Badge', 'verbose_name_plural': 'Badges'},
        ),
        migrations.AlterModelOptions(
            name='clothingitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Clothing Item', 'verbose_name_plural': 'Clothing Items'},
        ),
        migrations.AlterModelOptions(
            name='clothingrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Clothing Request', 'verbose_name_plural': 'Clothing Requests'},
        ),
        migrations.AlterModelOptions(
            name='exchange',
            options={'ordering': ['-created_at'], 'verbose_name': 'Exchange', 'verbose_name_plural': 'Exchanges'},
        ),
        migrations.AlterModelOptions(
            name='itemimage',
            options={'ordering': ['-is_primary', 'uploaded_at'], 'verbose_name': 'Item Image', 'verbose_name_plural': 'Item Images'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='userbadge',
            options={'ordering': ['-earned_at'], 'verbose_name': 'User Badge', 'verbose_name_plural': 'User Badges'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='badge',
            name='color',
            field=models.CharField(default='#4a6fa5', help_text='Hex color code', max_length=7),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=500),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.CharField(help_text='Font Awesome icon class', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/%Y/%m/%d/', validators=[core.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='clothing_items/%Y/%m/%d/', validators=[core.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('one-size', 'One Size')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/', validators=[core.models.validate_image_size]),
        ),
    ]
