# Generated by Django 5.2.7 on 2025-10-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='last_notification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='notification_frequency',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='immediate', max_length=10),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='receive_exchange_notifications',
            field=models.BooleanField(default=True, verbose_name='Exchange Activities'),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='receive_request_updates',
            field=models.BooleanField(default=True, verbose_name='Clothing Requests'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='receive_community_news',
            field=models.BooleanField(default=True, verbose_name='Community News'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='receive_donation_updates',
            field=models.BooleanField(default=True, verbose_name='New Donations'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='receive_new_items_alerts',
            field=models.BooleanField(default=True, verbose_name='New Items'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='unsubscribe_token',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
