# Generated by Django 5.2.7 on 2025-10-28 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_newslettersubscriber_last_notification_sent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='notification_frequency',
        ),
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='receive_exchange_notifications',
        ),
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='receive_request_updates',
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='receive_donation_updates',
            field=models.BooleanField(default=True, verbose_name='Donation Updates'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='receive_new_items_alerts',
            field=models.BooleanField(default=True, verbose_name='New Items Alerts'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
