# Generated by Django 5.2.7 on 2025-10-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_newslettersubscriber_notification_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='deactivation_reason',
            field=models.CharField(blank=True, choices=[('user_deletion', 'User Account Deleted'), ('manual', 'Manual Deactivation'), ('expired', 'Auto-expired')], max_length=50),
        ),
        migrations.AddField(
            model_name='clothingrequest',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('user_deletion', 'User Account Deleted'), ('manual', 'Manual Cancellation'), ('expired', 'Auto-expired')], max_length=50),
        ),
        migrations.AddField(
            model_name='clothingrequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('user_deletion', 'User Account Deleted'), ('manual', 'Manual Cancellation'), ('agreement', 'Mutual Agreement')], max_length=50),
        ),
        migrations.AddField(
            model_name='exchange',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
