# Generated by Django 5.2.7 on 2025-10-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_clothingitem_deactivated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='receive_exchange_notifications',
            field=models.BooleanField(default=True, verbose_name='Exchange Notifications'),
        ),
    ]
