# Generated by Django 5.2.7 on 2025-10-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_newslettersubscriber_receive_exchange_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='receive_request_updates',
            field=models.BooleanField(default=True, verbose_name='Clothing Request Updates'),
        ),
    ]
