# Generated by Django 5.2.7 on 2025-11-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_newslettersubscriber_receive_request_updates'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchange',
            unique_together=set(),
        ),
    ]
