"""
Django settings for clothingshareprj project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*1ihil(n@8wliktg00m**yoaln)+!uwq$u21#j=-uki3ak1r)4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ✅ FIXED: Added development hosts to prevent reload errors
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '0.0.0.0']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Added for password reset functionality

    'core.apps.CoreConfig',
    'userauths',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'clothingshareprj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',  # Add this for media URL access in templates
            ],
        },
    },
]

WSGI_APPLICATION = 'clothingshareprj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

# Media files (User uploaded images)
MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


JAZZMIN_SETTINGS = {
    "site_header": "Share Donation",
    "site_brand": "Donate Now",
    "site_logo": "assets/images/logo.png",  
    "copyright": "cloth_share.com",
}

AUTH_USER_MODEL = 'userauths.User'

# ✅ ADDED: Authentication Settings - FIXES LOGIN REDIRECT ISSUES
LOGIN_URL = '/auth/sign-in/'
LOGIN_REDIRECT_URL = '/profile/'
LOGOUT_REDIRECT_URL = '/'

# ✅ ADDED: Session settings for better security
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_SAVE_EVERY_REQUEST = True


# Email Configuration for Gmail (REAL CREDENTIALS)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'clothshareinfo@gmail.com'
EMAIL_HOST_PASSWORD = 'pqimlvsexviqpbac'  # App password without spaces

# Customize the from email
DEFAULT_FROM_EMAIL = 'ClothShare <clothshareinfo@gmail.com>'
SERVER_EMAIL = 'ClothShare <clothshareinfo@gmail.com>'

# ✅ ADDED: Admin email for notifications - FIXES EMAIL DELIVERY ISSUES
ADMIN_EMAIL = 'clothshareinfo@gmail.com'

# Site information (required for password reset)
SITE_ID = 1

# Password reset timeout (in seconds) - 24 hours
PASSWORD_RESET_TIMEOUT = 86400

# ✅ ADDED: Newsletter-specific settings
SITE_URL = 'http://127.0.0.1:8000'  # For unsubscribe links in emails
NEWSLETTER_FROM_EMAIL = 'ClothShare Newsletter <clothshareinfo@gmail.com>'
NEWSLETTER_ADMIN_EMAILS = ['clothshareinfo@gmail.com']

# ✅ ADDED: Newsletter preference defaults (for when users manually subscribe)
NEWSLETTER_DEFAULT_PREFERENCES = {
    'receive_donation_updates': True,
    'receive_exchange_notifications': False,  # Default to False for privacy
    'receive_new_items_alerts': True,
    'receive_community_news': True,
    'receive_request_updates': False,  # Default to False to avoid spam
}

# Media files configuration for development
# This ensures Django serves media files when DEBUG = True
if DEBUG:
    # Import here to avoid circular imports
    from django.conf.urls.static import static
    # This will be used in urls.py to serve media files
    MEDIA_URL_CONFIG = static(MEDIA_URL, document_root=MEDIA_ROOT)
else:
    MEDIA_URL_CONFIG = []

# ✅ ADDED: Enhanced logging configuration for better error handling
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'newsletter': {
            'format': '{levelname} {asctime} [Newsletter] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'debug.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
        },
        'newsletter_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'newsletter.log'),
            'formatter': 'newsletter',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'core': {
            'handlers': ['file', 'console', 'mail_admins'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file', 'console', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'core.services.notification_service': {
            'handlers': ['newsletter_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ✅ ADDED: Security settings for production readiness
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True

# ✅ ADDED: Email timeout settings to prevent hanging requests
EMAIL_TIMEOUT = 30  # seconds

# ✅ ADDED: CSRF trusted origins for production (when you deploy)
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    # Add your production domain when you deploy
    # 'https://yourdomain.com',
]